config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('materials/', include('materials.urls', namespace='materials')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from main.apps import MainConfig
from main.views import index, contact, StudentDetailView, StudentCreateView, StudentListView, StudentUpdateView, \
    StudentDeleteView, toggle_activity

app_name = MainConfig.name

urlpatterns = [
    path('', StudentListView.as_view(), name='index'),
    # path('', cache_page(60) (StudentListView.as_view()), name='index'),
    path('contact/', contact, name='contact'),
    path('view/<int:pk>/', StudentDetailView.as_view(), name='view_student'),
    path('create/', StudentCreateView.as_view(), name='create_student'),
    path('update/<int:pk>/', StudentUpdateView.as_view(), name='update_student'),
    path('delete/<int:pk>/', StudentDeleteView.as_view(), name='delete_student'),
    path('activity/<int:pk>/', toggle_activity, name='toggle_activity'),

]

materials/urls.py
from django.urls import path

from materials.apps import MaterialsConfig
from materials.views import MaterialCreateView, MaterialListView, MaterialDetailView, MaterialUpdateView, \
    MaterialDeleteView

app_name = MaterialsConfig.name

urlpatterns = [
    path('create/', MaterialCreateView.as_view(), name='create'),
    path('', MaterialListView.as_view(), name='list'),
    path('view/<int:pk>/', MaterialDetailView.as_view(), name='view'),
    path('edit/<int:pk>/', MaterialUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>/', MaterialDeleteView.as_view(), name='delete'),
]

materials/models.py
from django.db import models


class Material(models.Model):
    title = models.CharField(max_length=150, verbose_name='Name')
    body = models.TextField(verbose_name='Content')

    views_count = models.IntegerField(default=0, verbose_name='Views')
    is_published = models.BooleanField(default=True, verbose_name='Published')
    slug = models.CharField(max_length=150, verbose_name='slug', null=True, blank=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Material'
        verbose_name_plural = 'Materialy'

materials/views.py
from django.urls import reverse_lazy, reverse
from django.utils.text import slugify
from django.views import View
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView

from materials.models import Material


class MaterialCreateView(CreateView):
    model = Material
    extra_context = {'title': 'Create Material'}
    fields = ('title', 'body',)
    success_url = reverse_lazy('materials:list')

    def form_valid(self, form):
        if form.is_valid():
            new_mat = form.save()
            new_mat.slug = slugify(new_mat.title)
            new_mat.save()

        return super().form_valid(form)


class MaterialUpdateView(UpdateView):
    model = Material
    extra_context = {'title': 'Update Material'}
    fields = ('title', 'body',)
    # success_url = reverse_lazy('materials:list')

    def form_valid(self, form):
        if form.is_valid():
            new_mat = form.save()
            new_mat.slug = slugify(new_mat.title)
            new_mat.save()

        return super().form_valid(form)

    def get_success_url(self):
        return reverse('materials:view', args=[self.kwargs.get('pk')])


class MaterialListView(ListView):
    model = Material
    extra_context = {'title': 'Material List'}

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(is_published=True)
        return queryset


class MaterialDetailView(DetailView):
    model = Material
    extra_context = {'title': 'Material Detail'}

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save()
        return self.object


class MaterialDeleteView(DeleteView):
    model = Material
    extra_context = {'title': 'Delete Material'}
    success_url = reverse_lazy('materials:list')

materials/templates/materials/material_confirm_delete.html
  {% extends 'main/base.html' %}

{% block content %}
    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            <p>Material "{{ object.title }}" wirklich löschen?</p>
                            <button type="submit" class="btn btn-danger">Bestätigen</button>
                            <a href="{% url 'materials:list' %}" class="btn btn-warning">Abbrechen</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

materials/templates/materials/material_detail.html
{% extends 'main/base.html' %}

{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3>
                        Material "{{ object.title }}"
                    </h3>
                    <h4>Slug: {{ object.slug }}</h4>
                </div>
                <div class="card-body">
                    <p>
                        {{ object.body }}
                    </p>
                </div>
                <div class="card-footer">
                    Views: {{ object.views_count}}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

materials/templates/materials/material_form.html
{% extends 'main/base.html' %}

{% block content %}
    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-success">
                                {% if object %}
                                    Speichern
                                {% else %}
                                    Erstellen
                                {% endif %}
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

materials/templates/materials/material_list.html
{% extends 'main/base.html' %}
{% block content %}
  <div class="col-12 mb-5">
    <a class="btn btn-outline-primary" href="{% url 'materials:create' %}">Add Material</a>
  </div>
  {% for object in object_list %}
  <div class="col-md-4">
    <div class="card mb-4 box-shadow">
      <div class="card-body">
          <p class="card-text">
              {{ object|title }}
          </p>
            <div class="d-flex justify-content-between align-items-center">
            <div class="btn-group">
              <a href="{% url 'materials:view' object.pk %}"
                class="btn btn-sm btn-outline-secondary">View</a>
                <a href="{% url 'materials:edit' object.pk %}"
                class="btn btn-sm btn-outline-secondary">Edit</a>
              <a href="{% url 'materials:delete' object.pk %}"
                class="btn btn-sm btn-outline-danger">Delete</a>
          </div>
        </div>
      </div>
    </div>
  </div>
  {% endfor %}
  {% endblock%}