config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('materials/', include('materials.urls', namespace='materials')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from main.apps import MainConfig
from main.views import index, contact, StudentDetailView, StudentCreateView, StudentListView, StudentUpdateView, \
    StudentDeleteView, toggle_activity

app_name = MainConfig.name

urlpatterns = [
    path('', StudentListView.as_view(), name='index'),
    # path('', cache_page(60) (StudentListView.as_view()), name='index'),
    path('contact/', contact, name='contact'),
    path('view/<int:pk>/', StudentDetailView.as_view(), name='view_student'),
    path('create/', StudentCreateView.as_view(), name='create_student'),
    path('update/<int:pk>/', StudentUpdateView.as_view(), name='update_student'),
    path('delete/<int:pk>/', StudentDeleteView.as_view(), name='delete_student'),
    path('activity/<int:pk>/', toggle_activity, name='toggle_activity'),

]

main/models.py
from django.db import models

NULLABLE = {'blank': True, 'null': True}


class Student(models.Model):

    firstname = models.CharField(max_length=100, verbose_name='Vorname')
    lastname = models.CharField(max_length=100, verbose_name='Nachname')
    avatar = models.ImageField(upload_to='students/', verbose_name='Avatar', **NULLABLE)

    email = models.CharField(max_length=150, verbose_name='email', unique=True, **NULLABLE)

    is_active = models.BooleanField(default=True, verbose_name='studying')

    def __str__(self):
        return f'{self.firstname} {self.lastname}'

    class Meta:
        verbose_name = 'Student'
        verbose_name_plural = 'Studenten'
        ordering = ('lastname',)


class Subject(models.Model):
    title = models.CharField(max_length=150, verbose_name='name')
    description = models.TextField(verbose_name='description')

    student = models.ForeignKey(Student, on_delete=models.CASCADE, verbose_name='student')

    def __str__(self):
        return f'{self.title}'

    class Meta:
        verbose_name = 'Subject'
        verbose_name_plural = 'Subjects'

main/forms.py
from django import forms

from main.models import Student, Subject


class StyleFormMixin():
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class StudentForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Student
        # fields = '__all__'
        fields = ('firstname', 'lastname', 'avatar', 'email',)
        # exclude = ('is_active',)

    def clean_email(self):
        cleaned_data = self.cleaned_data['email']
        if 'test.test' not in cleaned_data:
            raise forms.ValidationError('not valid email. should contain test.test')
        return cleaned_data


class SubjectForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Subject
        fields = '__all__'

main/views.py
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin
from django.core.cache import cache
from django.forms import inlineformset_factory
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import DetailView, CreateView, ListView, UpdateView, DeleteView

from config import settings
from main.forms import StudentForm, SubjectForm
from main.models import Student, Subject


@login_required
def index(request):
    students_list = Student.objects.all()
    context = {
        'object_list': students_list,
    }

    return render(request, 'main/student_list.html', context)


class StudentCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Student
    # fields = ('firstname', 'lastname', 'avatar')
    form_class = StudentForm
    permission_required = 'main.add_student'
    success_url = reverse_lazy('main:index')
    extra_context = {'title': 'Create Student'}


class StudentListView(LoginRequiredMixin, ListView):
    model = Student
    extra_context = {'title': 'Student List'}


@login_required
@permission_required('main.view_student')
def contact(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        email = request.POST.get('email')
        message = request.POST.get('message')
        print(f'{name}: ({email}): {message}')

    context = {
        'title': 'Contact'
    }
    return render(request, 'main/contact.html', context)


class StudentDetailView(LoginRequiredMixin, PermissionRequiredMixin, DetailView):
    model = Student
    permission_required = 'main.view_student'
    extra_context = {'title': 'Student Details'}

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        key = f'subject_list_{self.object.pk}'
        if settings.CACHE_ENABLED:
            subject_list = cache.get(key)
            if subject_list is None:
                subject_list = self.object.subject_set.all()
                cache.set(key, subject_list)
        else:
            subject_list = self.object.subject_set.all()

        context_data['subject'] = subject_list
        return context_data



class StudentUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Student
    # fields = ('firstname', 'lastname', 'avatar')
    form_class = StudentForm
    permission_required = 'main.change_student'
    success_url = reverse_lazy('main:index')
    extra_context = {'title': 'Update Student'}

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        SubjectFormset = inlineformset_factory(Student, Subject, form=SubjectForm, extra=1)
        if self.request.method == 'POST':
            context_data['formset'] = SubjectFormset(self.request.POST, instance=self.object)
        else:
            context_data['formset'] = SubjectFormset(instance=self.object)
        return context_data

    def form_valid(self, form):
        formset = self.get_context_data()['formset']
        self.object = form.save()
        if formset.is_valid():
            formset.instance = self.object
            formset.save()
        return super().form_valid(form)


class StudentDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Student
    # permission_required = 'main.delete_student'
    success_url = reverse_lazy('main:index')
    extra_context = {'title': 'Delete Student'}

    def test_func(self):
        return self.request.user.is_superuser


@login_required
@permission_required('main.change_student')
def toggle_activity(request, pk):
    student_item = get_object_or_404(Student, pk=pk)
    if student_item.is_active:
        student_item.is_active = False
    else:
        student_item.is_active = True

    student_item.save()

    return redirect(reverse('main:index'))

main/templates/main/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{{ title }}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/album.css' %}" rel="stylesheet">
  </head>

  <body>

    <header>
      <div class="collapse bg-dark" id="navbarHeader">
        <div class="container">
          <div class="row">
            <div class="col-sm-8 col-md-7 py-4">
            </div>
              {% include 'main/includes/inc_main_menu.html' %}
          </div>
        </div>
      </div>
      <div class="navbar navbar-dark bg-dark box-shadow">
        <div class="container d-flex justify-content-between">
          <a href="#" class="navbar-brand d-flex align-items-center">
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="mr-2"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"></path><circle cx="12" cy="13" r="4"></circle></svg>
            <strong>Album</strong>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
        </div>
      </div>
    </header>

    <main role="main">

      <section class="jumbotron text-center">
        <div class="container">
          <h1 class="jumbotron-heading">{{ title }}</h1>

        </div>
      </section>

      <div class="album py-5 bg-light">
        <div class="container">

          <div class="row">

            {% block content%}
            {% endblock %}

          </div>
        </div>
      </div>
    </main>

    <footer class="text-muted">
      <div class="container">
        <p class="float-right">
          <a href="#">Back to top</a>
        </p>
        <p>&copy; {% now 'Y' %}</p>
      </div>
    </footer>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>

    <script src="{% static 'popper.min.js' %}""></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'holder.min.js' %}""></script>
  </body>
</html>

main/templates/main/contact.html
    {% extends 'main/base.html' %}

    {% block content %}
    <div class="col-md-4">
        <div class="card mb-4 box-shadow">
            <div class="card-body">
                <p class="card-text">
                   Office BER <br>
                   Ofiice MUC

                </p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="card mb-4 box-shadow">
            <div class="card-body">
              <h2>Contact Us</h2>
                <form method="post">
                  <input class="form-control mb-2" name="name">
                  <input class="form-control mb-2" name="email">
                  <textarea class="form-control mb-2" name="message"></textarea>
                  <button type="submit" class="btn btn-primary form-control mb-2">Send</button>
                </form>
            </div>
        </div>
    </div>
    {% endblock %}

main/templates/main/student_confirm_delete.html
  {% extends 'main/base.html' %}

{% block content %}
    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            <p>Studenten "{{ object.firstname }} {{ object.lastname }}" wirklich löschen?</p>
                            <button type="submit" class="btn btn-danger">Bestätigen</button>
                            <a href="{% url 'main:index' %}" class="btn btn-warning">Abbrechen</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

main/templates/main/student_detail.html
{% extends 'main/base.html' %}

{% block content %}
    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">
                            Information über den Studenten
                        </h3>
                    </div>
                    <div class="card-body">
                        <table class="table">
                            <tr>
                                <td>Vorname</td>
                                <td>{{ object.firstname }}</td>
                            </tr>
                            <tr>
                                <td>Nachname</td>
                                <td>{{ object.lastname }}</td>
                            </tr>
                            <tr>
                                <td>eMail</td>
                                <td></td>
                            </tr>
                        </table>
                    </div>
                </div>
            </div>
            <div class="col-6">
               <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">
                            Fächer des Studenten
                        </h3>
                    </div>
                    <div class="card-body">
                        <ul>
                            {% for subject in subject %}
                            <li>{{ subject }}</li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

main/templates/main/student_form.html
{% extends 'main/base.html' %}

{% block content %}

<div class="col-12">
    <form class="row" method="post" enctype="multipart/form-data">

            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">
                            Add Student
                        </h3>
                    </div>
                    <div class="card-body">

                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-primary">
                                {% if object %}
                                    Speichern
                                {% else %}
                                    Erstellen
                                {% endif %}
                            </button>
                    </div>
                    <div class="card-footer"></div>
                </div>
            </div>

        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                        Add Subject
                    </h3>
                </div>
                <div class="card-body">
                    {{ formset.management_form }}
                    {% for form in formset.forms %}
                        {{ form.as_p }}
                    {% if not forloop.last %}
                        <hr>
                    {% endif %}
                    {% endfor %}
                </div>
                <div class="card-footer"></div>
                </div>
            </div>
        </div>
    </form>
</div>

{% endblock %}

main/templates/main/student_list.html
{% extends 'main/base.html' %}
{% block content %}
<div class="col-12 mb-5">
    {% if perms.main.add_student %}
    <a class="btn btn-outline-primary" href="{% url 'main:create_student' %}">Create Student</a>
    {% endif%}
  </div>
  {% for object in object_list %}
  <div class="col-md-4">
    <div class="card mb-4 box-shadow">
    <div class="card-header"># {{object.pk}}</div>
      <div class="card-body">
          <p class="card-text">
            {% if object.is_active%}
              {{ object|title }}
            {% else %}
              <span class="text-muted">{{ object|title }}</span>
            {% endif%}
          </p>
            <div class="card-footer">
            <div class="d-flex justify-content-between align-items-center">
            <div class="btn-group">
              {% if perms.main.view_student %}
              <a href="{% url 'main:view_student' object.pk %}"
                class="btn btn-sm btn-outline-secondary">View</a>
              {% endif %}
              {% if perms.main.change_student %}
              <a href="{% url 'main:update_student' object.pk %}"
                class="btn btn-sm btn-outline-secondary">Edit</a>
              {% endif %}
              {% if user.is_superuser %}
              <a href="{% url 'main:delete_student' object.pk%}"
                class="btn btn-sm btn-outline-danger">Delete</a>
              {% endif %}
          </div>
            {% if perms.main.change_student %}
              {% if object.is_active %}
                <a class="btn btn-warning" href="{% url 'main:toggle_activity' object.pk %}">deactivate</a>
              {% else %}
                <a class="btn btn-success" href="{% url 'main:toggle_activity' object.pk %}">activate</a>
              {% endif %}
            {% endif %}
        </div>
      </div>
      </div>
    </div>
  </div>
  {% endfor %}
  {% endblock%}